### ISSUE TITLE
Are someone using?

### ISSUE THREAD

**Issue by felipeuntill** [caravel-tool/caravel#11]
Are someone currently using caravel in production? i think that is a really good idea but i found soo many missing features to be a production ready project. 
What the project administrators thinks about it and what you guys intend with the project.

**Comment by kazzkiq** [comment]
**Are someone currently using caravel in production?**
As far as I know, there isn't. The project wasn't quite "production-ready" yet, and the website is still in development, so I don't believe much people even know about Caravel, let alone use it.

**I think that is a really good idea but I found so many missing features to be a production ready project**
Caravel started as an open-source alternative to automated deployment tools such as [CodeShip](https://codeship.com/). The main idea behind it was to make easier to run simple deployment tasks and check for any errors, without having to use paid services to do that.

As a side project, it started (and still is) small. As for now, the project focus would be summed up on those steps:

1. Grab a Node project;
2. Try to deploy it on a production server;
3. Report any errors in the proccess and block failed builds.

To meet these steps, Caravel needs to be able to fetch projects from Git, install dependencies and run tasks defined by the users in the configuration file (`caravel.json`).

All help is wanted, and feature proposals are also welcomed from anyone (althought they may not be implemented until the above steps are finished).

**I found soo many missing features to be a production ready project**
@felipeuntill What do you think we should add to Caravel in order to make it more attractive to new users?
